CREATE TABLE NOTICE
(
     ID		NUMBER,
     TITLE 		NVARCHAR2(100),
     WRITER_ID	NVARCHAR2(50),
     CONTENT	CLOB,
     REGDATE  	TIMESTAMP,
     HIT		NUMBER,
     FILES		NVARCHAR2(1000)
);

--> list 출력 SQL문 작성.
select ID, TITLE, WRITER_ID, CONTENT, REGDATE, HIT, FILES
from NOTICE order by REGDATE desc;

--> 공지사항 등록
	INSERT INTO NOTICE (ID, TITLE, WRITER_ID, CONTENT, REGDATE, HIT, FILES) 
	VALUES (NOTICE_ID_SEQ.NEXTVAL, '영원한 사랑', 'kwonpro', '프로그램에 대한 사랑은 영원하여라!! ㅋㅋ', SYSDATE, 0 ,'');
    
    commit;
    
    SELECT ID, TITLE, WRITER_ID, CONTENT, REGDATE, HIT, FILES
	from NOTICE order by REGDATE DESC;



CREATE TABLE "COMMENT"
(
     ID		NUMBER,
     CONTENT	NVARCHAR2(2000),
     REGDATE  	TIMESTAMP,
     WRITER_ID	NVARCHAR2(50),
     NOTICE_ID	NUMBER
);

CREATE TABLE ROLE
(
     ID		VARCHAR2(50),
     DISCRIPTION 	NVARCHAR2(500)
);

CREATE TABLE MEMBER_ROLE
(
     MEMBER_ID	NVARCHAR2(50),
     ROLE_ID		VARCHAR2(50)
);